### PR TITLE
Asset money unit tests

### PR DESCRIPTION
**Pull request by bitcoinbrisbane**
Some unit tests on the Asset money class.  Also refactor ToString overrides to use String.Format.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Thanks !

**Comment by NicolasDorier** [comment]
btw, you should make branches everytimes you prepare a PR. Because you'll get problem if you are working on several stuff at the same time and want to make different PR for them. You'll get also problem if for some reason I don't merge one of your PR.

**Comment by NicolasDorier** [comment]
`git checkout -b yourbranchname` do your stuff....
And when you want to go back to master
`git branch master`
If you want to update your master with this repo:

https://help.github.com/articles/syncing-a-fork/

(The article assume you did `git remote add upstream https://github.com/NicolasDorier/NBitcoin.git` before

**Comment by bitcoinbrisbane** [comment]
Agreed. Though this just a quick set of changes

On 1 Jul 2015, at 7:12 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:


git checkout -b yourbranchname do your stuff....
And when you want to go back to master
git branch master
If you want to update your master with this repo:

https://help.github.com/articles/syncing-a-fork/

(The article assume you did git remote add upstream https://github.com/NicolasDorier/NBitcoin.git before

-

**Comment by bitcoinbrisbane** [comment]
Is there some place to discuss changes and ideas? NBitcoin forum?

I started a GitHub wiki too. Your book is great, but a wiki might be easier to share code samples etc.  just an idea

On 1 Jul 2015, at 7:12 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:


git checkout -b yourbranchname do your stuff....
And when you want to go back to master
git branch master
If you want to update your master with this repo:

https://help.github.com/articles/syncing-a-fork/

(The article assume you did git remote add upstream https://github.com/NicolasDorier/NBitcoin.git before

-

**Comment by NicolasDorier** [comment]
Ideas can be discussed in issues, but you are right a forum and wiki is a good idea.
In fact I started making a website for nbitcoin but got a bit busy lately.

**Comment by bitcoinbrisbane** [comment]
Ok. Well your project is saving me a lot of dev effort so I'm quite keen to invest a lot of time back towards NBitcoin.

I'll keep working on code coverage and small refactors

On 1 Jul 2015, at 9:29 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:


Ideas can be discussed in issues, but you are right a forum and wiki is a good idea.
In fact I started making a website for nbitcoin but got a bit busy lately.

-

**Comment by NicolasDorier** [comment]
thanks ! what do you propose I setup as wiki and forum ? I'm not used setting up that, what is the right tool for the job ?

**Comment by bitcoinbrisbane** [comment]
Github has a wiki built in, i added a few test pages last night.

Im sure azure has a forum in its gallery we could deploy quickly.

**Comment by NicolasDorier** [comment]
ok thanks I'll do that, let me know if you need any right on github wiki

**Comment by lontivero** [comment]
We need a mail list, a group in goggle or an slack team (I prefer the latest one). I've created a team (https://nbitcoin.slack.com). I need your emails to invite you. If you don't like it or prefer something different, a google group could fit. What do you think about this?

**Comment by NicolasDorier** [comment]
as we talked, discussing code on github (via issues and PR) is better for collaboration and accessible to search engines.

I'll make a simple forum, or ask space on bitcointalk.

**Pull request merged**
