### PR TITLE
- bugfix: set StartsWith functions to InvariantCulture

### PR DESCRIPTION
**Pull request by nopara73**
http://stackoverflow.com/a/29925279/2061103

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Like I said, I will merge that but I'd like to understand the root cause. As you can see, "mechanism", is taken in an array where every value is already uppercase. Can you give me your System.Threading.Thread.CurrentThread.CurrentUICulture, so I can make a test ?

**Comment by nopara73** [comment]
I have added this stackoverflow link as a comment to my pull request, this
is not the original thread: http://stackoverflow.com/a/29925279/2061103
With these lines you can easily get back the bug.

There is nothing wrong with uppercase. For some reason the StartsWith
function doesn't work as expected, and I mean it very literally.

2015-04-29 2:49 GMT+08:00 Nicolas Dorier <notifications@github.com>:

> Like I said, I will merge that but I'd like to understand the root cause.
> As you can see, "mechanism", is taken in an array where every value is
> already uppercase. Can you give me your
> System.Threading.Thread.CurrentThread.CurrentUICulture, so I can make a
> test ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NicolasDorier/NBitcoin/pull/73#issuecomment-97168228>.
>



-- 
Üdv,
Ádám

btc:1EPRH4Zt6FDQibS57d7NL9fb5fDcjjaqqp

**Comment by NicolasDorier** [comment]
I will fix that with OrdinalIgnoreCase instead of InvariantCulture (or your code does not compile fine in portable libraries)

Can you give me your System.Threading.Thread.CurrentThread.CurrentUICulture, this bug should definitively be in my "best gotcha" list.

**Comment by NicolasDorier** [comment]
Ok, for history.

> Thread.CurrentThread.CurrentCulture = new CultureInfo("hu");
string mechanism = "HMACSHA256";
var v1 = mechanism.StartsWith("HMAC");
mechanism = "HMAC-SHA256";
var v2 = mechanism.StartsWith("HMAC");

In hungarian, v1 is false and v2 true.

**Comment by NicolasDorier** [comment]
I close this PR, I used Ordinal instead of InvariantCulture for portability issues. 1.0.8.18 on nuget include the patch. (Update-Package NBitcoin)

Thanks for the report.

**Comment by nopara73** [comment]
Yes, it works with OrdinalIgnoreCase, too.

Here's my CurrentUICulture:
(CultureInfo ci = System.Threading.Thread.CurrentThread.CurrentUICulture;)

- ci {en-US} System.Globalization.CultureInfo
+ Calendar {System.Globalization.GregorianCalendar}
System.Globalization.Calendar
{System.Globalization.GregorianCalendar}
+ CompareInfo {CompareInfo - en-US} System.Globalization.CompareInfo
CultureTypes SpecificCultures | InstalledWin32Cultures | FrameworkCultures
System.Globalization.CultureTypes
+ DateTimeFormat {System.Globalization.DateTimeFormatInfo}
System.Globalization.DateTimeFormatInfo
DisplayName "English (United States)" string
EnglishName "English (United States)" string
IetfLanguageTag "en-US" string
IsNeutralCulture false bool
IsReadOnly true bool
KeyboardLayoutId 1033 int
LCID 1033 int
Name "en-US" string
NativeName "English (United States)" string
+ NumberFormat {System.Globalization.NumberFormatInfo}
System.Globalization.NumberFormatInfo
+ OptionalCalendars {System.Globalization.Calendar[2]}
System.Globalization.Calendar[]
+ Parent {en} System.Globalization.CultureInfo
+ TextInfo {TextInfo - en-US} System.Globalization.TextInfo
ThreeLetterISOLanguageName "eng" string
ThreeLetterWindowsLanguageName "ENU" string
TwoLetterISOLanguageName "en" string
UseUserOverride true bool
- Static members
+ CurrentCulture {hu-HU} System.Globalization.CultureInfo
+ CurrentUICulture {en-US} System.Globalization.CultureInfo
+ DefaultThreadCurrentCulture null System.Globalization.CultureInfo
+ DefaultThreadCurrentUICulture null System.Globalization.CultureInfo
+ InstalledUICulture {en-US} System.Globalization.CultureInfo
+ InvariantCulture {} System.Globalization.CultureInfo
+ Non-Public members
+ Non-Public members

2015-04-29 9:35 GMT+08:00 Nicolas Dorier <notifications@github.com>:

> I will fix that with OrdinalIgnoreCase instead of InvariantCulture (or
> your code does not compile fine in portable libraries)
>
> Can you give me your
> System.Threading.Thread.CurrentThread.CurrentUICulture, this bug should
> definitively be in my "best gotcha" list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NicolasDorier/NBitcoin/pull/73#issuecomment-97280852>.
>



-- 
Üdv,
Ádám

btc:1EPRH4Zt6FDQibS57d7NL9fb5fDcjjaqqp

**Comment by nopara73** [comment]
Thank you for solving this issue. I'll make pull-requests if I encounter
with something similar. Here's my sumup to stackoverflow:
http://stackoverflow.com/a/29933353/2061103

2015-04-29 10:05 GMT+08:00 Adam Ficsor <adam.ficsor73@gmail.com>:

> Yes, it works with OrdinalIgnoreCase, too.
>
> Here's my CurrentUICulture:
> (CultureInfo ci = System.Threading.Thread.CurrentThread.CurrentUICulture;)
>
> - ci {en-US} System.Globalization.CultureInfo
> + Calendar {System.Globalization.GregorianCalendar} System.Globalization.Calendar
> {System.Globalization.GregorianCalendar}
> + CompareInfo {CompareInfo - en-US} System.Globalization.CompareInfo
> CultureTypes SpecificCultures | InstalledWin32Cultures | FrameworkCultures
> System.Globalization.CultureTypes
> + DateTimeFormat {System.Globalization.DateTimeFormatInfo}
> System.Globalization.DateTimeFormatInfo
> DisplayName "English (United States)" string
> EnglishName "English (United States)" string
> IetfLanguageTag "en-US" string
> IsNeutralCulture false bool
> IsReadOnly true bool
> KeyboardLayoutId 1033 int
> LCID 1033 int
> Name "en-US" string
> NativeName "English (United States)" string
> + NumberFormat {System.Globalization.NumberFormatInfo}
> System.Globalization.NumberFormatInfo
> + OptionalCalendars {System.Globalization.Calendar[2]}
> System.Globalization.Calendar[]
> + Parent {en} System.Globalization.CultureInfo
> + TextInfo {TextInfo - en-US} System.Globalization.TextInfo
> ThreeLetterISOLanguageName "eng" string
> ThreeLetterWindowsLanguageName "ENU" string
> TwoLetterISOLanguageName "en" string
> UseUserOverride true bool
> - Static members
> + CurrentCulture {hu-HU} System.Globalization.CultureInfo
> + CurrentUICulture {en-US} System.Globalization.CultureInfo
> + DefaultThreadCurrentCulture null System.Globalization.CultureInfo
> + DefaultThreadCurrentUICulture null System.Globalization.CultureInfo
> + InstalledUICulture {en-US} System.Globalization.CultureInfo
> + InvariantCulture {} System.Globalization.CultureInfo
> + Non-Public members
> + Non-Public members
>
> 2015-04-29 9:35 GMT+08:00 Nicolas Dorier <notifications@github.com>:
>
>> I will fix that with OrdinalIgnoreCase instead of InvariantCulture (or
>> your code does not compile fine in portable libraries)
>>
>> Can you give me your
>> System.Threading.Thread.CurrentThread.CurrentUICulture, this bug should
>> definitively be in my "best gotcha" list.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NicolasDorier/NBitcoin/pull/73#issuecomment-97280852>
>> .
>>
>
>
>
> --
> Üdv,
> Ádám
>
> btc:1EPRH4Zt6FDQibS57d7NL9fb5fDcjjaqqp
>



-- 
Üdv,
Ádám

btc:1EPRH4Zt6FDQibS57d7NL9fb5fDcjjaqqp

**Pull request closed without merging**
