### PR TITLE
Small refactors

### PR DESCRIPTION
**Pull request by bitcoinbrisbane**
Rename filename to match class name.  Check via String.IsNullOrEmpty and unit test.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I thing you forgot to include the TokenizeTask file to the commit.
Also, I would prefer throwing FormatException (like it should be now) rather than NullArgumentException if the string is null. I think we should keep the null check how it was.

**Comment by bitcoinbrisbane** [comment]
Sorry, I didn't commit the build.proj file.  

I didn't change the exception type. I was just asserting on Empty Strings as well as null strings.  The base 58 WIF key can't really be "", so may as well check for that?

**Comment by NicolasDorier** [comment]
Normally, if the string is empty, it should throw FormatException, not ArgumentNullException.
This is what is happening if you don't replace by String.IsNullOrEmpty because of the Base58 Encoder.

**Comment by lontivero** [comment]
Just an opinion: the build project is useful for one and only one developer. It shouldn't be in this repo.

**Comment by NicolasDorier** [comment]
Well, I don't necessarily agree since at one point I may use a public build server and thus it will need this project. It also allow you to publish your own package if it is different from mine.

**Comment by bitcoinbrisbane** [comment]
@NicolasDorier re exceptions, I agree.  I guess its up to you.  Just trying to get good code coverage on this project.

**Comment by bitcoinbrisbane** [comment]
@NicolasDorier re build\TokinizeTask.cs, git is complaining that the path is part of the ignore.  Want me to push anyway?

**Comment by bitcoinbrisbane** [comment]
Ok, I've pushed the TokenizeTask.cs file.  

Also included in this pull request (sorry I wanted to make a new one but it went into this one automatically) is the ability to generate a Multisig script using third parties PubKey.  There would be use cases where you don't know the users Key.  
780028afeea924870ab58876f45a9473154ab1c9

**Comment by bitcoinbrisbane** [comment]
Sorry, I now see that the Key class can be instantiated with a Byte[].  Happy to revert.

**Comment by NicolasDorier** [comment]
Yes can you revert 780028a ? `PayToMultiSigTemplate` already takes care of generating multi sig scripts.

**Comment by bitcoinbrisbane** [comment]
Done.  Sorry about that.

________________________________

**Comment by NicolasDorier** [comment]
no problem, also, in BitcoinAddress.cs, you should not check String.IsNullOrEmpty but as it was before.
NullArgumentException when the argument is not null will confuse debugging sessions. The tests are useful.

Once you have that, can you rebase your commit so we get nice history ?
`git rebase -i HEAD~X` where X is the number of commit which belongs to this PR.

**Comment by bitcoinbrisbane** [comment]
No worries, Ill do that now.  Happy to help get the code coverage up to around 80% too.


Sorry, im a bit of a github novice.  Its now popped up a VIM window.  Now what do i do?


https://help.github.com/articles/about-git-rebase/doesnt seem to help.

About Git rebase - User Documentation
The git rebase command allows you to easily change a series of commits, modifying the history of your repository. You can reorder, edit, or squash commits together.Typically, you would use ...
Read more...<https://help.github.com/articles/about-git-rebase/>



________________________________

**Comment by bitcoinbrisbane** [comment]
Ok, i think Ive got it.  Ill squash and reword the comments.

________________________________

**Comment by NicolasDorier** [comment]
yeah, vim is a pain when you don't know how to use but actually it is easy

You press 'i' to get in insert mode. You change your stuff, the ':wq' to validate.

**Comment by NicolasDorier** [comment]
@bitcoinbrisbane do you manage to rebase ?

**Comment by bitcoinbrisbane** [comment]
I thought I did.  I went through the vim, changed all but top to squash.  Re commented and pushed.

**Comment by NicolasDorier** [comment]
you did not, look at all the commits of the PR.

Here is what you should do:

`git rebase -i HEAD~11`
Because there is 11 commits.
then change to 'f' all the commits after the first one.
`:wq`
then change/put your comment.
`:wq`
then push
`git push --force`

Let me know if it helps,

**Comment by bitcoinbrisbane** [comment]
rebase
This was the output

**Comment by NicolasDorier** [comment]
did you `git push --force` alternatively you can give me access to your repo so I can make the change and show you how to do for next time.

**Comment by bitcoinbrisbane** [comment]
That might be easier for now.  Ive added you to my repo.

**Comment by NicolasDorier** [comment]
Sorry, I messed up the rebase :/
I will do it manually on my repo instead of merging this PR.

**Comment by NicolasDorier** [comment]
AAAH no I fixed it ! (by mistake when I wanted to remove the mess I had done)

**Comment by NicolasDorier** [comment]
Please for next time, create a new branch for your PR, it makes things simpler.

**Comment by bitcoinbrisbane** [comment]
Agreed

On 28 Jun 2015, at 8:19 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:


Please for next time, create a new branch for your PR, it makes things simpler.

-

**Pull request merged**
