### PR TITLE
Using BufferedStream for socket communication

### PR DESCRIPTION
**Pull request by lontivero**
Take a look at these changes. The Buffer size needs to be tunned better, 50kb is the best value for sure. (Only for discussion)

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I've benchmarked it, I don't see any obvious performance improvements, so I would prefer we don't use it.
But I like the fact that ReadNext do not depends on Socket anymore.
Is it possible to remove the BufferedStream but keep the rest ?

image

**Comment by lontivero** [comment]
I've remove the BufferedStream and include changes in Hex and Base58 encoders. Also, Message.ReadNext() is overloaded with Stream and Socket.

**Comment by NicolasDorier** [comment]
Can you remove the Hex and Base58 part for now ?
I'm bothered by the fact that Hex now require a list, this class is used a lot for intensive indexing applications, and would not require lots of overhead.
Hex encoder is used an order of magnitude more than base58, because it is the most common way to serialize any bitcoin structure.

Maybe we should not change it after all.

**Comment by lontivero** [comment]
Yes, I can. But let me do a benchmark first.

**Comment by lontivero** [comment]
Well, you were right about the hex encoder performance. The problem was not because of the List but the extra comparisons instead.

**Comment by NicolasDorier** [comment]
and also that accessing a list with an index is O(n)

**Pull request merged**
