### PR TITLE
RPC AddNode, GetAddedNodeInfo, BackupWallet and EstimatePriority

### PR DESCRIPTION
**Pull request by lontivero**
@NicolasDorier, I'm sending the PR for review and discussion.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
This is a good idea, but should have the async versions too.

Also, the IpEndpoint class is not portable. For RestClient, I only used `#if !NOSOCKET` to disable any code coupled with IpEndpoint. But it sucks to delete code, just because IpEndpoint is not available in portable library. I'm not sure about the best way to handle this problem.

I can't test for now, my node is indexing transactions :-S

**Comment by lontivero** [comment]
In the latest commit I moved code for grouping it in code regions. I did it to have a better idea about the  implemented and missing RPC methods. I know this makes the review harder but on the other hand the code is easier to find and work with.

**Comment by NicolasDorier** [comment]
Can you wrap `return GetAddedNodeInfoAsync(detailed).Result;` correctly so we get back a real exception and not a generic aggregate exception ? I did it several time in RPCClient, and RestClient you should find an example.

**Comment by lontivero** [comment]
@NicolasDorier, this PR is done since yesterday. Could you review it?

**Comment by NicolasDorier** [comment]
trait should be [Trait("RPCClient", "RPCClient")], I am using it for my build server.

Some .Result are still not wrapped (EstimatePriority)

**Comment by lontivero** [comment]
Done.

**Comment by NicolasDorier** [comment]
last nit, you use %temp% in the test, can you just use the relative path (which will resolve to the output dir of the test project) ?

**Comment by lontivero** [comment]
Sure, no problem. It is an important point.

**Pull request merged**
