### PR TITLE
Change default maximum OP_RETURN size to 80 bytes

### PR DESCRIPTION
**Pull request by lontivero**
@NicolasDorier, the change in this PR is correct.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
The limit is always 40 bytes in 0.11, even if master says it is not. Look at the tagged version.

**Comment by lontivero** [comment]
It was introduced in the [bitcoin core 0.11 RC - file: /src/script/standard.h](https://github.com/bitcoin/bitcoin/blob/v0.11.0rc1/src/script/standard.h) 

```
static const unsigned int MAX_OP_RETURN_RELAY = 80;      //! bytes
```

As you well said, it is not 80 bytes (yet). Let the PR opened

**Comment by NicolasDorier** [comment]
good to know, also I don't know if it is a good idea to move it to 80 bytes before we get a majority of 0.11 nodes. What do you think ?

**Comment by lontivero** [comment]
NBitcoin won't break backward compatibility with this change and at the same time it will be able to accept transactions broadcasted by clients which take advantage of the new script max size.

I think that, given this is a protocol change, NBitcoin should be updated to understand the new protocol versions, by going hand in hand with the latest official bitcoin core release version. (no release candidate but final releases).

IMO you should do the same that the bitcoin core team did: take this change wait for the official bitcoin realease. Once the 0.11 release is publish, you could release a new NBitcoin version too.

**Comment by NicolasDorier** [comment]
ok so I let this PR open until then ?

**Comment by lontivero** [comment]
Yes, IMO that's ok.

**Comment by NicolasDorier** [comment]
0.11 is released

**Pull request merged**
